
###
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "username": "souli",
  "password": "password"
}

###
POST {{baseUrl}}/login/login
Content-Type: application/json

{
  "username": "SOULI",
  "password": "password"
}

###
POST {{baseUrl}}/login/login
Content-Type: application/json

{
  "username": "bri",
  "password": "Mdpuser.1"
}

###
POST {{baseUrl}}/login/login
Content-Type: application/json

{
  "username": "gregreg",
  "password": "passwordd"
}
