###
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "username":"Stal",
  "password":"password",
  "firstName": "guillaume",
  "lastName": "bouillon",
  "street": "Rue de la trouille",
  "buildingNumber": 8,
  "unitNumber": 12,
  "postcode":1235,
  "city": "mashala Land"
}